packages:
  - apps/*
  - packages/*

catalog:
  # dependencies
  vue: ^3.5.34
  # devDependencies
  '@types/node': ^25.8.0
  '@vitejs/plugin-vue': ^6.0.7
  '@vue/tsconfig': ^0.9.1
  typescript: ^6.0.3
  vite: ^8.0.13
  vue-tsc: ^3.2.9
ignoredBuiltDependencies: # 这些包有问题，暂时不构建

onlyBuiltDependencies:
