/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideUser: typeof import('./src/components/AsideUser.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LogCard: typeof import('./src/components/LogCard.vue')['default']
    LogCardMedias: typeof import('./src/components/LogCardMedias.vue')['default']
    LogEditor: typeof import('./src/components/LogEditor.vue')['default']
    LogEditorAudios: typeof import('./src/components/LogEditorAudios.vue')['default']
    LogEditorFiles: typeof import('./src/components/LogEditorFiles.vue')['default']
    LogEditorMedias: typeof import('./src/components/LogEditorMedias.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
  }
}
