/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(default)': RouteRecordInfo<
      '/(default)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(default)/'
      | '/(default)/log'
      | '/(default)/map'
      | '/(default)/mine'
      | '/(default)/profile'
    >,
    '/(default)/': RouteRecordInfo<
      '/(default)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/log': RouteRecordInfo<
      '/(default)/log',
      '/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/map': RouteRecordInfo<
      '/(default)/map',
      '/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/mine': RouteRecordInfo<
      '/(default)/mine',
      '/mine',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(default)/profile': RouteRecordInfo<
      '/(default)/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test': RouteRecordInfo<
      '/test',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(default).vue': {
      routes:
        | '/(default)'
        | '/(default)/'
        | '/(default)/log'
        | '/(default)/map'
        | '/(default)/mine'
        | '/(default)/profile'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/(default)/index.vue': {
      routes:
        | '/(default)/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(default)/log.vue': {
      routes:
        | '/(default)/log'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(default)/map.vue': {
      routes:
        | '/(default)/map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(default)/mine.vue': {
      routes:
        | '/(default)/mine'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(default)/profile.vue': {
      routes:
        | '/(default)/profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/test.vue': {
      routes:
        | '/test'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
